version: '3.4'

services:
  parkingapp:
    image: parkingapp
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5002:5002
      
    
  db:
    image: postgres:14
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
    