"""empty message

Revision ID: 21e0851135a7
Revises: e652bc6f00f1
Create Date: 2022-09-25 23:32:49.886204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21e0851135a7'
down_revision = 'e652bc6f00f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('counties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('county_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('county_name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('phone_number', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('places',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('place_name', sa.String(), nullable=False),
    sa.Column('county_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['county_id'], ['counties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('place_name')
    )
    op.create_table('lots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('place_id', sa.Integer(), nullable=True),
    sa.Column('lot_number', sa.String(), nullable=False),
    sa.Column('lot_price', sa.Float(), nullable=False),
    sa.Column('current_use', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lot_number')
    )
    op.create_table('reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_category', sa.String(), nullable=False),
    sa.Column('vehicle_plate', sa.String(), nullable=True),
    sa.Column('reserve_date', sa.String(), nullable=False),
    sa.Column('start_time', sa.String(), nullable=False),
    sa.Column('end_time', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reserve_id', sa.Integer(), nullable=True),
    sa.Column('reservation_fees', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['reserve_id'], ['reservations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.drop_table('reservations')
    op.drop_table('lots')
    op.drop_table('places')
    op.drop_table('users')
    op.drop_table('counties')
    # ### end Alembic commands ###
